# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RW3uNE6p_joXccuN34NlsVVK7314CA5_
"""

# -*- coding: utf-8 -*-
"""
app.py
HEMS 排程最佳化展示平台：結合設備開關的動態負載模擬與 PSO 排程分析
"""
import streamlit as st
import pandas as pd
import numpy as np
import plotly.express as px
import matplotlib.pyplot as plt

# 匯入您的核心演算法包
import hems_pso_core

# ============================================================
# 1. 網頁基本設定與資料定義
# ============================================================
st.set_page_config(page_title="智慧家庭能源管理系統", layout="wide", page_icon="⚡")

# 設備清單定義 (保留您的設定)
APPLIANCES = {
    'fridge': {'name': '變頻冰箱', 'color': '#06b6d4'},
    'ac': {'name': '客廳變頻冷氣', 'color': '#3b82f6'},
    'heater': {'name': '儲熱式電熱水器', 'color': '#ea580c'},
    'dehumidifier': {'name': '除濕機 (自動)', 'color': '#22c55e'},
    'dryer': {'name': '熱泵烘衣機', 'color': '#84cc16'},
    'lighting': {'name': '全棟照明', 'color': '#facc15'},
    'washer': {'name': '洗衣機', 'color': '#a855f7'},
    'transferPump': {'name': '揚水馬達', 'color': '#0ea5e9'},
    'boosterPump': {'name': '加壓馬達', 'color': '#f59e0b'},
}

DATA_PATH = "daily_appliance_data_1min.csv"

# ============================================================
# 2. 資料讀取與快取處理
# ============================================================
# 為了避免每次點擊開關都重新讀取大檔案，使用 @st.cache_data
@st.cache_data
def load_base_data(path):
    """讀取基礎的 1 分鐘解析度資料 (假設您的原始資料是長這樣)"""
    try:
        # 這裡請根據您實際的資料格式進行調整
        df = pd.read_csv(path)
        # 確保有 Time 欄位，如果沒有，這裡我們模擬一個作為範例展示
        if 'Time' not in df.columns:
             # 模擬 24小時，1分鐘一筆 = 1440 筆
            df['Time'] = pd.date_range("2026-05-17", periods=len(df), freq="min")
        return df
    except Exception as e:
        st.error(f"無法讀取資料檔 {path}。錯誤訊息: {e}")
        return None

# ============================================================
# 3. 側邊欄：執行狀態看板
# ============================================================
st.sidebar.title("⚡ 系統大腦核心")
st.sidebar.markdown("本區監控 PSO 粒子群演算法的即時運算狀態。")
status_placeholder = st.sidebar.empty() # 預留空間放狀態訊息

# ============================================================
# 4. 主畫面 - 上半部：智慧負載模擬區
# ============================================================
st.title("智慧家庭負載模擬與 BESS 最佳化排程")
st.markdown("---")

df_base = load_base_data(DATA_PATH)

if df_base is not None:
    st.subheader("🏠 步驟一：調整家庭負載情境")

    # 使用比例 3:1 分割畫面
    col_chart, col_controls = st.columns([3, 1])

    with col_controls:
        st.write("##### 🎛️ 設備控制開關")
        st.caption("勾選以模擬設備運轉")
        # 建立開關，預設全開
        active_items = {k: st.checkbox(v['name'], value=True) for k, v in APPLIANCES.items()}

    with col_chart:
        # 根據開關狀態建立新的 DataFrame
        df_plot = df_base.copy()
        active_keys = [k for k, v in active_items.items() if v and k in df_plot.columns]

        # 將沒勾選的設備用電歸零
        for key in APPLIANCES.keys():
            if key in df_plot.columns and not active_items[key]:
                df_plot[key] = 0

        # 計算新的總用電
        available_keys = [k for k in APPLIANCES.keys() if k in df_plot.columns]
        df_plot['Total_W'] = df_plot[available_keys].sum(axis=1)

        # 繪製 Plotly 圖表
        if active_keys:
            fig = px.area(
                df_plot,
                x='Time',
                y=active_keys,
                color_discrete_map={k: v['color'] for k, v in APPLIANCES.items()}
            )
            fig.update_layout(
                hovermode="x unified",
                margin=dict(l=0, r=0, t=30, b=0),
                height=350 # 讓圖不要太高
            )
            st.plotly_chart(fig, use_container_width=True)
        else:
            st.info("請至少開啟一項設備。")


    # ============================================================
    # 5. 銜接 PSO 演算法與資料預處理 (修改後)
    # ============================================================
    st.markdown("---")
    st.subheader("🤖 步驟二：PSO 儲能排程最佳化")

    try:
        # 將 1 分鐘的總負載轉為 24 小時陣列
        hourly_load = df_plot['Total_W'].values.reshape(-1, 60).mean(axis=1) / 1000.0
    except:
        st.warning("資料格式非標準 1440 筆，使用簡化重取樣。")
        hourly_load = df_plot['Total_W'].values[:24] / 1000.0 

    status_placeholder.info("🔄 偵測到負載變更，PSO 重新計算中...")
    with st.spinner("PSO 演算法運算中..."):
        # 直接將 hourly_load 陣列傳入核心演算法，不需經過 CSV
        data_package = hems_pso_core.run_optimization_pipeline(hourly_load)
    
    status_placeholder.success("✅ 計算完成！")


    # ============================================================
    # 6. 主畫面 - 下半部：成果展示
    # ============================================================

    before_result = data_package["before_result"]
    after_result = data_package["after_result"]
    convergence_curve = data_package["convergence_curve"]

    # 側邊欄指標更新 (假設 result 裡面有記錄成本)
    st.sidebar.subheader("📊 經濟效益評估")
    before_cost = before_result.get("total_cost", 100) # 預設值防呆
    after_cost = after_result.get("total_cost", 80)

    st.sidebar.metric(
        label="優化後日電費",
        value=f"NT$ {after_cost:.2f}",
        delta=f"- NT$ {before_cost - after_cost:.2f} ({(before_cost-after_cost)/max(before_cost, 1)*100:.1f}%)",
        delta_color="inverse" # 越低越好
    )


    # 圖表分頁
    tab1, tab2 = st.tabs(["🔋 儲能系統 (BESS) 狀態", "📉 演算法收斂歷程"])

    with tab1:
        st.write("#### 電池充放電功率與電網購電狀態")
        # 這裡請替換成您實際想畫的內容
        fig_bess, ax1 = plt.subplots(figsize=(10, 4))

        # 假設 after_result 裡有 p_grid 陣列
        if 'p_grid_curve' in after_result:
             ax1.plot(after_result['p_grid_curve'], label='Grid Power', color='red')

        # 假設 after_result 裡有 bess 功率陣列
        # ax1.bar(range(24), after_result['bess_power'], label='BESS Power', color='green')

        ax1.set_xlabel("Hour")
        ax1.set_ylabel("Power (kW)")
        ax1.grid(True)
        ax1.legend()
        st.pyplot(fig_bess)

    with tab2:
        st.write("#### PSO 最佳化過程")
        fig_conv, ax_conv = plt.subplots(figsize=(10, 4))
        ax_conv.plot(convergence_curve, color='blue', linewidth=2, label='Best Fitness')
        ax_conv.set_title("PSO 收斂曲線")
        ax_conv.set_xlabel("Iteration")
        ax_conv.set_ylabel("Fitness Value")
        ax_conv.grid(True)
        st.pyplot(fig_conv)